# Generated by Django 3.0.1 on 2020-01-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='emailAdderss',
            new_name='emailAddress',
        ),
    ]
