# Generated by Django 3.0.1 on 2020-01-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20200110_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingPostCode',
            new_name='billingPostcode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingPostCode',
            new_name='shippingPostcode',
        ),
    ]
